apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: { app: backend }
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: {{ .Values.images.backend }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
          env:
            - name: NEO4J_URI
              value: {{ .Values.backend.env.NEO4J_URI | quote }}
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-auth
                  key: NEO4J_PASSWORD
          resources:
{{- toYaml .Values.backend.resources | nindent 12 }}
