apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  type: ClusterIP
  selector: { app: frontend }
  ports:
    - name: http
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
